### ISSUE TITLE
Some arcs may have incorrect reference vector

### ISSUE THREAD

**Issue by JoeLambourne** [ChrisWu1997/DeepCAD#6]
Hi DeepCAD Team,

I'm plotting some parts of your data and I believe in some cases the definition of `Arc3D` may be incorrect.   For example I am analyzing json file `00057168.json` sketch `Fr8CL4J6BeRGSeU_3` profile  `JSa`.   
![00057168_Fr8CL4J6BeRGSeU_3_JSa](https://user-images.githubusercontent.com/17026486/154253428-c93e30f0-7253-482d-b255-eb85e01d661c.png)
Looking at this file in the ABC dataset I see
![image](https://user-images.githubusercontent.com/17026486/154253529-9f0187c2-432b-4015-9b7e-8ff1088e115b.png)
I think the profile in question came from the yellow shape.

My understanding of the dataset is that the reference vector can be used to understand which segment of the circle forms the arc.   The reference vector is a 2D vector in the sketch plane coordinate system.  The visible segment of the arc is anti-clockwise from the reference vector.   The sweep angle is defined by `end_angle`.   For the top arc in the 2D image at the start of this post we have

```
        {
         "center_point": {
          "y": -0.20581618,
          "x": -0.07702744,
          "z": 0.0
         },
         "start_point": {
          "y": -0.18829072,
          "x": -0.04397157,
          "z": 0.0
         },
         "start_angle": 0.0,
         "end_point": {
          "y": -0.16869228,
          "x": -0.0816803,
          "z": 0.0
         },
         "normal": {
          "y": 0.0,
          "x": 0.0,
          "z": 1.0
         },
         "curve": "JSF",
         "end_angle": 5.07520255726804,
         "radius": 0.03741434,
         "type": "Arc3D",
         "reference_vector": {
          "y": 0.9922371231467976,
          "x": -0.12436032908193387,
          "z": 0.0
         }
        }
```
So the sweep angle is bigger than pi and the large half of the arc is incorrectly chosen.

Do you have any strategy for determining the correct segment of the arc?

Thank you for your help.

**Comment by JoeLambourne** [comment]
Thank you for looking.   Calling `evEdgeTangentLine` looks like it should work.   Maybe a bug in OnShape.   Arcs are notoriously bad for bugs in CAD systems.  Is there a way to get the start and end parameter value of the arc without using the `arcLengthParameterization` option.   The bug might be in the OnShape arc length computation.

**Comment by ChrisWu1997** [comment]
After taking a deeper look, I think both the data parsing and arc interpretation are correct. The misunderstanding comes from the definition of sketch profile. 

The sketch is composed of multiple profiles, each is a region enclosed by one or more edge loops. And we did not merge those profiles, even though they are extruded by the same extrusion operation (following the convention of onshape API). What you visualized above is just one profile `JSa` of the entity `Sketch 5`. 

See below for illustration. If you search for the major arc `JSF` in the json file, you will find it appears in both profiles `JSa` and `JSO`.

![image](https://user-images.githubusercontent.com/32172140/154770559-370806a4-13b5-4723-914c-f2d062885818.png)

**Comment by JoeLambourne** [comment]
@ChrisWu1997,

Thank you for the detailed explanation.   This makes a lot of sense.   Yes.  he shape I'm expecting will be the union of all the profiles extruded by that operation.  Let's close this as the solution is going to be to perform some post processing.
