### ISSUE TITLE
About the augmentation technique

### ISSUE THREAD

**Issue by Ma-Weijian** [ChrisWu1997/DeepCAD#7]
Hi Chris,

I found that you have adopted the data augmentation technique in your paper and achieved even better result than the standard model. However, it happened that the data augmentation technique does not appear in this repository.

I wonder if the data augmentation technique appears in the repository or in somewhere else. If not, how can I augment the data myself?

Thanks and best regards.

Weijian Ma

**Comment by ChrisWu1997** [comment]
Hi,

I have just added the augmentation code [here](https://github.com/ChrisWu1997/DeepCAD/blob/1194724783949ecede31c2241ca472acfa92ceaf/dataset/cad_dataset.py#L44). From my experience, the data augmentation only improves the auto encoding results, but not the generation results, as the data augmentation is kind of random (augmented CAD model might be unnatural).

**Comment by Ma-Weijian** [comment]
Thanks a lot for the code!
