### ISSUE TITLE
Regarding Point Cloud Reconstruction

### ISSUE THREAD

**Issue by Danelrf** [ChrisWu1997/DeepCAD#9]
Hello ,

Apologies as my question is not purely related to DeepCAD, but is of extreme importance to me.

Would it be possible to know what software or library you used to carry out point cloud reconstruction as shown in Figure 6 of the paper?

I would really appreciate this info. 

Thank you again, and truly amazing work!

**Comment by ChrisWu1997** [comment]
Do you mean the rendering of point clouds? The reconstruction is performed by our methods. Those are some selected examples, in general our method is not designed for point cloud reconstruction.

**Comment by Danelrf** [comment]
Oh, I understand.

You use PointNet++ to encode and embed the point cloud to your latent vector, and then use your own autoencoder to generate the CAD solid.

At first I understood it was a visualization for comparison purposes.

Thank you for your clarification.

**Comment by ChrisWu1997** [comment]
> You use PointNet++ to encode and embed the point cloud to your latent vector, and then use your own autoencoder to generate the CAD solid.

Yes, that's right.
